<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.4"/>
    <xacro:property name="chassis_width" value="0.25"/>
    <xacro:property name="chassis_height" value="0.16"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.03"/>
    <xacro:property name="wheel_thickness" value="0.03"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.165"/>
    <xacro:property name="wheel_offset_y" value="0.17"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <!-- <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/> -->

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>
    
    <material name="orange">
        <color rgba="1 0.3 0.1 1" />
    </material>
    
    <material name="blue">
        <color rgba="0.2 0.2 1 1" />
    </material>
    
    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <material name="red">
        <color rgba="1 0 0 1" />
    </material>

<!-- BASE LINK -->

    <link name="base_link">

    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

<!-- CHASSIS  LINK-->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

<!-- LEFT FRONT WHEEL -->

<!--  <joint name="left_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_front_wheel"/>
        <origin  xyz="0.165 0.14 -0.08" rpy="1.5708 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.03" length="0.03"/>
            </geometry>
            <material name="blue"/>    
        </visual>
-->

<link name="wheel_front_left_link">
  <visual>
    <geometry>
      <!-- <sphere radius="${wheel_radius}"/> -->
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/> <!-- agar menghadap ke samping -->
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <geometry>
      <sphere radius="${wheel_radius}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </geometry>
    <friction>
      <ode>
        <mu>1000000</mu>
        <mu2>1000000</mu2>
        <slip1>0.01</slip1>
        <slip2>0.01</slip2>
      </ode>
    </friction>
  </collision>
  <!-- <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05"> -->
  <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:inertial_cylinder>
</link>
<gazebo reference="wheel_front_left_link">
    <material>Gazebo/Blue</material>
</gazebo>
<joint name="base_to_wheel_front_left" type="continuous">
  <parent link="base_link"/>
  <child link="wheel_front_left_link"/>
  <origin xyz="${wheel_offset_x} ${wheel_offset_y} 0" rpy="-${pi/2} 0 0"/>
  <axis xyz="0 0 1"/>
</joint>

<!-- kanan-depan -->
<link name="wheel_front_right_link">
  <visual>
    <geometry>
      <!-- <sphere radius="${wheel_radius}"/> -->
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <geometry>
      <sphere radius="${wheel_radius}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </geometry>
    <friction>
      <ode>
        <mu>1000000</mu>
        <mu2>1000000</mu2>
        <slip1>0.01</slip1>
        <slip2>0.01</slip2>
      </ode>
    </friction>
  </collision>
  <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:inertial_cylinder>
</link>
<gazebo reference="wheel_front_right_link">
    <material>Gazebo/Blue</material>
</gazebo>
<joint name="base_to_wheel_front_right" type="continuous">
  <parent link="base_link"/>
  <child link="wheel_front_right_link"/>
  <origin xyz="${wheel_offset_x} ${-wheel_offset_y} 0" rpy="${pi/2} 0 0"/>
  <axis xyz="0 0 -1"/>
</joint>

<!-- kiri-belakang -->
<link name="wheel_back_left_link">
  <visual>
    <geometry>
      <!-- <sphere radius="${wheel_radius}"/> -->
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <geometry>
      <sphere radius="${wheel_radius}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </geometry>
    <friction>
      <ode>
        <mu>1000000</mu>
        <mu2>1000000</mu2>
        <slip1>0.01</slip1>
        <slip2>0.01</slip2>
      </ode>
    </friction>
  </collision>
  <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:inertial_cylinder>
</link>
<gazebo reference="wheel_back_left_link">
    <material>Gazebo/Blue</material>
</gazebo>
<joint name="base_to_wheel_back_left" type="continuous">
  <parent link="base_link"/>
  <child link="wheel_back_left_link"/>
  <origin xyz="${-wheel_offset_x} ${wheel_offset_y} 0" rpy="${pi/2} 0 0"/>
  <axis xyz="0 0 -1"/>
</joint>

<!-- kanan-belakang -->
<link name="wheel_back_right_link">
  <visual>
    <geometry>
      <!-- <sphere radius="${wheel_radius}"/> -->
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <geometry>
      <sphere radius="${wheel_radius}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </geometry>
    <friction>
      <ode>
        <mu>1000000</mu>
        <mu2>1000000</mu2>
        <slip1>0.01</slip1>
        <slip2>0.01</slip2>
      </ode>
    </friction>
  </collision>
  <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:inertial_cylinder>
</link>
<gazebo reference="wheel_back_right_link">
    <material>Gazebo/Blue</material>
</gazebo>
<joint name="base_to_wheel_back_right" type="continuous">
  <parent link="base_link"/>
  <child link="wheel_back_right_link"/>
  <origin xyz="${-wheel_offset_x} ${-wheel_offset_y} 0" rpy="${pi/2} 0 0"/>
  <axis xyz="0 0 -1"/>
</joint>


</robot>